[package]
name = "win_sig"
version = "0.2.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
kernel32-sys = "0.2.2"
lazy_static = "0.2.9"
winapi = "0.2.8"

[[example]]
name = "five_ctrl_c"